---
# tasks file for ansible-role-win-sqlserver-update
- name: Ensure extract dir exists
  ansible.windows.win_file:
    path: '{{ sql_server_update_extract_dir }}'
    state: directory

- name: Download PSTools
  ansible.windows.win_get_url:
    url: '{{ ps_tools_download_url }}'
    dest: '{{ sql_server_update_extract_dir }}\{{ ps_tools_filename_zip }}'
    validate_certs: '{{ sql_server_update_download_validate_certs }}'
    force: no

- name: PSTools - Unzip
  community.windows.win_unzip:
    src: '{{ sql_server_update_extract_dir }}\{{ ps_tools_filename_zip }}'
    dest: '{{ sql_server_update_extract_dir }}\'
    delete_archive: yes

- name: Download
  ansible.windows.win_get_url:
    url: '{{ sql_server_update_download_url }}'
    dest: '{{ sql_server_update_extract_dir }}\{{ sql_server_update_install_exe }}'
    validate_certs: '{{ sql_server_update_download_validate_certs }}'
    force: no

- name: Execute SQL Update
  ansible.windows.win_command: "{{ sql_server_update_install_command }}"
  #ansible.windows.win_command: '{{ sql_server_update_extract_dir }}\{{ sql_server_update_install_exe }} /IAcceptSQLServerLicenseTerms /Action=Patch /InstanceName=MSSQLSERVER /quiet'
  args:
    chdir: '{{ sql_server_update_extract_dir }}'
    # creates: '{{ sql_server_already_installed_path }}'
  register: sql_server_update_result
  failed_when: 
    - sql_server_update_result.rc != 0
    - sql_server_update_result.rc != 2252537859

- name: Debug sql_server_update_result
  ansible.builtin.debug:
    var: sql_server_update_result

- name: Reboot
  ansible.windows.win_reboot:
  when: sql_server_update_result.rc == 2252537859
...
